const jokes = [
  "Why don’t programmers like nature? Too many bugs.",
  "Why did the computer catch a cold? It left its Windows open.",
  "Why do Java developers wear glasses? Because they don’t C#.",
  "Why was the JavaScript developer sad? Because he didn’t know how to ‘null’ his feelings.",
  "Why did the programmer quit his job? Because he didn’t get arrays.",
  "Debugging: Being the detective in a crime movie where you are also the murderer.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "I told my computer I needed a break, and it said: ‘No problem, I’ll go to sleep.’",
  "Why did the function return early? It had a date.",
  "Why did the programmer go broke? He used up all his cache.",

  "Why was the cell phone wearing glasses? It lost its contacts.",
  "Why do programmers hate the outdoors? The sun causes glare on screens.",
  "Why did the array break up with the object? Too many properties.",
  "Why was the computer tired when it got home? It had too many tabs open.",
  "Why did the developer stay calm? He had good exception handling.",
  "Why did the loop get fired? It never stopped working.",
  "Why did the programmer bring a ladder? To reach the high-level language.",
  "Why did the bug cross the road? To crash on the other side.",
  "Why was the keyboard always calm? It had good control.",
  "Why did the coder go to therapy? Too many unresolved issues.",

  "Why did the database admin leave his wife? Too many relations.",
  "Why did the computer go to the dentist? Bluetooth.",
  "Why do programmers hate math? Because it has too many problems.",
  "Why was the JavaScript file so confident? It knew it was async.",
  "Why did the HTML break up with CSS? Too many style issues.",
  "Why was the server cold? It lost its cache.",
  "Why did the computer go to art school? To improve its graphics.",
  "Why do programmers prefer iOS? Fewer bugs… sometimes.",
  "Why did the programmer get stuck in the shower? The instructions said: Lather, Rinse, Repeat.",
  "Why don’t programmers like parties? Too many callbacks.",

  "Why did the laptop go to the gym? To get stronger RAM.",
  "Why did the code fail? It had too many assumptions.",
  "Why do programmers love coffee? Because Java.",
  "Why was the variable unhappy? It couldn’t find its value.",
  "Why did the developer go broke? He spent all his money on domains.",
  "Why did the computer sneeze? It caught a virus.",
  "Why did the programmer cross the road? To optimize the other side.",
  "Why was the computer bad at singing? It had no vocal range.",
  "Why did the coder love nature? Free Wi-Fi was the only problem.",
  "Why did the code go to jail? It broke the rules.",

  "Why do programmers hate meetings? They prefer stand-ups.",
  "Why did the monitor blush? It saw the desktop.",
  "Why was the algorithm so confident? It had a solid plan.",
  "Why did the coder refuse to sleep? He was running on caffeine.",
  "Why did the computer get glasses? It couldn’t C.",
  "Why did the website break? Too much traffic.",
  "Why was the loop lonely? No one ever joined it.",
  "Why did the coder bring snacks? For byte-sized meals.",
  "Why was the programmer bad at football? He kept missing the goal.",
  "Why did the code look messy? No proper formatting.",

  "Why did the app crash? Emotional overload.",
  "Why did the programmer sit near the AC? To avoid overheating.",
  "Why did the computer fail the exam? Too many errors.",
  "Why did the developer hate Sundays? No deploys allowed.",
  "Why did the code get promoted? It was well-structured.",
  "Why was the programmer calm during bugs? He expected them.",
  "Why did the software go to school? To improve its skills.",
  "Why did the coder use Linux? He liked freedom.",
  "Why did the computer feel powerful? It had admin rights.",
  "Why did the code break up? Compatibility issues.",

  "Why did the programmer stay up all night? To catch a bug.",
  "Why was the app so slow? It needed optimization.",
  "Why did the computer join a band? It had great keyboard skills.",
  "Why was the code always happy? No runtime errors.",
  "Why did the programmer love recursion? Because recursion.",
  "Why did the laptop cry? Someone closed it without saving.",
  "Why was the software confident? Version 2.0.",
  "Why did the programmer laugh at errors? He wrote them.",
  "Why did the code feel insecure? Too many dependencies.",
  "Why did the computer relax? No processes running."
];
let randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
console.log(randomJoke);

document.getElementById('joke').innerHTML = randomJoke

